spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campuswarning
    username: root
    password: 1234
    druid:
      min-idle: 10
      max-active: 100
      max-wait: 6000
      min-evictable-idle-time-millis: 3000000
      time-between-eviction-runs-millis: 60000
  mvc:
    path match:
      matching-strategy: ant_path_matcher


